// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: order_events.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_CREATED OrderStatus = 0
	OrderStatus_READY   OrderStatus = 1
	OrderStatus_COMING  OrderStatus = 2
	OrderStatus_DONE    OrderStatus = 3
	OrderStatus_RATED   OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "CREATED",
		1: "READY",
		2: "COMING",
		3: "DONE",
		4: "RATED",
	}
	OrderStatus_value = map[string]int32{
		"CREATED": 0,
		"READY":   1,
		"COMING":  2,
		"DONE":    3,
		"RATED":   4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_events_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_events_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_events_proto_rawDescGZIP(), []int{0}
}

type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=events.OrderStatus" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_order_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_order_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_order_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OrderEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderEvent) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_CREATED
}

func (x *OrderEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OrderEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RestId        string                 `protobuf:"bytes,2,opt,name=rest_id,json=restId,proto3" json:"rest_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedPayload) Reset() {
	*x = OrderCreatedPayload{}
	mi := &file_order_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedPayload) ProtoMessage() {}

func (x *OrderCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_order_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedPayload.ProtoReflect.Descriptor instead.
func (*OrderCreatedPayload) Descriptor() ([]byte, []int) {
	return file_order_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCreatedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCreatedPayload) GetRestId() string {
	if x != nil {
		return x.RestId
	}
	return ""
}

func (x *OrderCreatedPayload) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderReadyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestId        string                 `protobuf:"bytes,1,opt,name=rest_id,json=restId,proto3" json:"rest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReadyPayload) Reset() {
	*x = OrderReadyPayload{}
	mi := &file_order_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReadyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReadyPayload) ProtoMessage() {}

func (x *OrderReadyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_order_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReadyPayload.ProtoReflect.Descriptor instead.
func (*OrderReadyPayload) Descriptor() ([]byte, []int) {
	return file_order_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrderReadyPayload) GetRestId() string {
	if x != nil {
		return x.RestId
	}
	return ""
}

type OrderComingPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     string                 `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderComingPayload) Reset() {
	*x = OrderComingPayload{}
	mi := &file_order_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderComingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderComingPayload) ProtoMessage() {}

func (x *OrderComingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_order_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderComingPayload.ProtoReflect.Descriptor instead.
func (*OrderComingPayload) Descriptor() ([]byte, []int) {
	return file_order_events_proto_rawDescGZIP(), []int{4}
}

func (x *OrderComingPayload) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

type OrderDonePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     string                 `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDonePayload) Reset() {
	*x = OrderDonePayload{}
	mi := &file_order_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDonePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDonePayload) ProtoMessage() {}

func (x *OrderDonePayload) ProtoReflect() protoreflect.Message {
	mi := &file_order_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDonePayload.ProtoReflect.Descriptor instead.
func (*OrderDonePayload) Descriptor() ([]byte, []int) {
	return file_order_events_proto_rawDescGZIP(), []int{5}
}

func (x *OrderDonePayload) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

type OrderRatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        uint32                 `protobuf:"varint,1,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	RestaurantId  string                 `protobuf:"bytes,3,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRatedPayload) Reset() {
	*x = OrderRatedPayload{}
	mi := &file_order_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRatedPayload) ProtoMessage() {}

func (x *OrderRatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_order_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRatedPayload.ProtoReflect.Descriptor instead.
func (*OrderRatedPayload) Descriptor() ([]byte, []int) {
	return file_order_events_proto_rawDescGZIP(), []int{6}
}

func (x *OrderRatedPayload) GetRating() uint32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *OrderRatedPayload) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *OrderRatedPayload) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

var File_order_events_proto protoreflect.FileDescriptor

const file_order_events_proto_rawDesc = "" +
	"\n" +
	"\x12order_events.proto\x12\x06events\"\xa7\x01\n" +
	"\n" +
	"OrderEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.events.OrderStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\";\n" +
	"\tOrderItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"p\n" +
	"\x13OrderCreatedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\arest_id\x18\x02 \x01(\tR\x06restId\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.events.OrderItemR\x05items\",\n" +
	"\x11OrderReadyPayload\x12\x17\n" +
	"\arest_id\x18\x01 \x01(\tR\x06restId\"3\n" +
	"\x12OrderComingPayload\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\"1\n" +
	"\x10OrderDonePayload\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\"j\n" +
	"\x11OrderRatedPayload\x12\x16\n" +
	"\x06rating\x18\x01 \x01(\rR\x06rating\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12#\n" +
	"\rrestaurant_id\x18\x03 \x01(\tR\frestaurantId*F\n" +
	"\vOrderStatus\x12\v\n" +
	"\aCREATED\x10\x00\x12\t\n" +
	"\x05READY\x10\x01\x12\n" +
	"\n" +
	"\x06COMING\x10\x02\x12\b\n" +
	"\x04DONE\x10\x03\x12\t\n" +
	"\x05RATED\x10\x04B9Z7github.com/Konscig/foodelivery-pet/internal/pb/eventspbb\x06proto3"

var (
	file_order_events_proto_rawDescOnce sync.Once
	file_order_events_proto_rawDescData []byte
)

func file_order_events_proto_rawDescGZIP() []byte {
	file_order_events_proto_rawDescOnce.Do(func() {
		file_order_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_events_proto_rawDesc), len(file_order_events_proto_rawDesc)))
	})
	return file_order_events_proto_rawDescData
}

var file_order_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_events_proto_goTypes = []any{
	(OrderStatus)(0),            // 0: events.OrderStatus
	(*OrderEvent)(nil),          // 1: events.OrderEvent
	(*OrderItem)(nil),           // 2: events.OrderItem
	(*OrderCreatedPayload)(nil), // 3: events.OrderCreatedPayload
	(*OrderReadyPayload)(nil),   // 4: events.OrderReadyPayload
	(*OrderComingPayload)(nil),  // 5: events.OrderComingPayload
	(*OrderDonePayload)(nil),    // 6: events.OrderDonePayload
	(*OrderRatedPayload)(nil),   // 7: events.OrderRatedPayload
}
var file_order_events_proto_depIdxs = []int32{
	0, // 0: events.OrderEvent.status:type_name -> events.OrderStatus
	2, // 1: events.OrderCreatedPayload.items:type_name -> events.OrderItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_events_proto_init() }
func file_order_events_proto_init() {
	if File_order_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_events_proto_rawDesc), len(file_order_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_events_proto_goTypes,
		DependencyIndexes: file_order_events_proto_depIdxs,
		EnumInfos:         file_order_events_proto_enumTypes,
		MessageInfos:      file_order_events_proto_msgTypes,
	}.Build()
	File_order_events_proto = out.File
	file_order_events_proto_goTypes = nil
	file_order_events_proto_depIdxs = nil
}
